language: java
jdk:
- oraclejdk8
- oraclejdk9
- openjdk8
script:
- ./gradlew release
after_success:
- scripts/ci/upload_test_coverage.sh
deploy:
  provider: releases
  api_key:
    secure: "MS6n8kIWSOsjdp8QGwuMe/XfVPaKICrqA2Y5Z3Cd6HWPLpg519mKY3GkiQCVvUgPOF3E3m6uGKKFVMX3DDMFefUqb3XxMICqGjE3rYCJY5f5rWOL0rBmboimjWcJjNUOSJGkIimeah3RMHq/0gCuhYTTTQLuP3lp7/4QNvWmSz4TcMrXDWNGyB+S7qZw1ltsK0avCU4/7SMe2Kbzo5u1ZJ7Vj3coyt1FGIzVtq3clF/gHi6RblbsUBWZAw7YePlb1d5fKJwlV9weK38GOk1DG3eOXmR5IN8yktwQcI+5K945olGyMUAvR0ojrDY3mL0cUUlPGmxiswRkgW8SrK7aS33Pj21KAy3/YGP9cgJ3kuPOwZIczkO/faDAWb2NLUqmSv3OVPFxmI+4F0GxryMVfru2qz+oD6nS6IJQ0ImJnzX1/hgOVH3u4xtc/xdGqOuW1Ah1ctItfoq0Vqd/lF4Vo2Ek/BUqVMzboBZJh6c9SH4P2mfSMu9jwGj0LC5gRtdSu6QUR642a6aebJjiB8UD/GIW17pgppNBc+4DYbSLj6XoF3Ok8fY8KPvgZJqJz3/lfmqPME6p1/X/sgpDDWaTuqrYZ6zmQK4up2/y8xrvrUBDL1buZaNz3DwXZo0doavkGQmOCGEnD/qnp327gN46WXATnHiCp6nPjDAcOo9Mkz0="
  skip_cleanup: true
  file:
  - build/distributions/identio-server.tar.gz
  - build/distributions/identio-server.zip  
  on:
    tags: true
    jdk: oraclejdk9
 